name: deploy-app

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened]

  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: job1
        run: echo "Deploying app"
