name: app-deploy

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened]

  push:
    branches:
      - main

job:
  test:
    runs on: Ubuntu 
    steps:
      - name: job1
        runs: echo "Deploying app"